### ISSUE TITLE
Side cogs spin the wrong way when scrolling

### ISSUE THREAD

**Issue by mysticuno** [techx/makemit-splash#1]
When scrolling through the page, the gears on the side of the page spin opposite the direction that they would IRL. When scrolling down, the left cog should rotate counterclockwise and the right cog should rotate clockwise. Likewise, when scrolling up, the left cog should rotate clockwise and the right cog should rotate counterclockwise.

I tried simply flipping the negatives on lines 27 and 28 of [main.js](https://github.com/techx/makemit-splash/blob/bbfef5af426bc0331477e8797d45bf794b4b2cde/js/main.js#L27L28), but then the alignment gets completely out of whack. I think it's due to the magic number on [line 26](https://github.com/techx/makemit-splash/blob/bbfef5af426bc0331477e8797d45bf794b4b2cde/js/main.js#L26), but I couldn't figure out how those values were calculated so I'd be shooting blindly if I tried to change them by hand.

**Comment by Detry322** [comment]
wat I dont have this problem at all

**Comment by Detry322** [comment]
maybe scrolling too fast and it's updating to make it look like its going the wrong way?

**Comment by mysticuno** [comment]
Huh, so if I scroll down with arrow keys or slowly with a trackpad, then it seems to scroll the right way, but when I scroll with a mouse wheel it looks as if it's scrolling the wrong way

**Comment by mysticuno** [comment]
Also, it seems to scroll the right way on mobile as well (though mobile right now looks a bit sad). I guess it's just a problem with people using mice. `--wont-fix`

**Comment by rneogy** [comment]
Mousewheel jumps lines so it makes it look like its scrolling the wrong
way. If you use trackpad or any smooth scrolling it should be fine. Please
don't adjust the magic numbers - they work for now, and I can explain how I
got them, but mostly it was through a lot of manual testing. I know this
isn't the best way, but when I tried doing the math for it, it never worked
lol.

Basically, if it ain't broke, don't fix it.
